# Generated by Django 4.1.10 on 2023-08-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('iin', models.CharField(blank=True, max_length=8, unique=True)),
                ('cost', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_sold', models.IntegerField(default=0)),
                ('selling_price', models.PositiveIntegerField()),
                ('profit_earned', models.IntegerField(default=0)),
                ('revenue', models.IntegerField(default=0)),
            ],
        ),
    ]
